### PR TITLE
Added Kernel to sponsors

### PR DESCRIPTION
**Pull request by kevinlu1248**

### CODE REVIEW

**Review by kx-chen — CHANGES_REQUESTED** [review]
hackhub logo isn't supposed to be there. not too sure what happened but it looks like you might've forgotten to rebase your branch. get the commit history fixed and the changes should be good

**Comment by kevinlu1248** [comment]
Fixed Hackhub Logo and removed Student Ambassador section. Haven't fixed the history but everything else is okay

**Review by kx-chen — COMMENTED** [review]
Looks good, but the hackhub logo is smaller now according to the diff. Take a look?

**Comment by kx-chen** [comment]
@kevinlu1248 Friendly bump :)

**Comment by kevinlu1248** [comment]
I will try to get to it today @kx-chen

**Comment by kevinlu1248** [comment]
Fixed Hackhub size @kx-chen can you check over?

**Review by kx-chen — APPROVED** [review]

**Pull request merged**
