### PR TITLE
Added Hackhub logo

### LINKED ISSUE #5: Add HackHub Logo
80663050_2464038253849463_688075970095087616_n

Add the HackHub logo to the sponsors section on the website.

### PR DESCRIPTION
**Pull request by kevinlu1248**
Can you also give GitKraken access to this repo? Thanks!

Closes #5

### CODE REVIEW

**Review by kx-chen — CHANGES_REQUESTED** [review]
Screen Shot 2019-12-24 at 5 55 45 PM

The logo is a bit small on my screen, do you mind making it a bit bigger. Setting a certain width or height should do the trick. 

Other than that, it looks good. Nice!

**Comment by kevinlu1248** [comment]
Sorry didn't catch that earlier but it is fixed now.

**Review by kx-chen — APPROVED** [review]
LGTM!

Just make sure for next time to keep commit messages and titles in the current tense. ("Add Hackhub logo" instead of "Added"). It makes it easier to read when someone goes through the commit log. You should also make branch names somewhat reflective of the changes (something like `add-hackhub-logo`)

Also, it's more of a preference, but I usually like to keep everything in one commit instead of adding them on top of each other, so you can commit with `--amend` and force push so that you don't push up extra commits. (it also makes it easier to review when the changes get large)

Up to you though :)

Sorry for the long paragraph LOL

Great job!!! 🥇

**Comment by kx-chen** [comment]
Also, logo position should be fine where it is :)

**Pull request merged**
